#!/bin/bash
TERM=dumb sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
sed -i 's/robbyrussell/mh/' ~/.zshrc
usermod root -s /bin/zsh
locale-gen --purge en_US.UTF-8
